### ISSUE TITLE
After Update, lot of errors and break up

### ISSUE THREAD

**Issue by dehenne** [AegeusCoin/aegeus#6]
After the Update to 1.2 i get lot of errors and the deamon dies. :(

```
/usr/include/c++/4.8/debug/safe_iterator.h:506:error: attempt to compare a 
    dereferenceable iterator to a singular iterator.

Objects involved in the operation:
iterator "lhs" @ 0x0x7fd5faff6db0 {
type = N11__gnu_debug14_Safe_iteratorIN9__gnu_cxx17__normal_iteratorIP11CMasternodeNSt9__cxx19986vectorIS3_SaIS3_EEEEENSt7__debug6vectorIS3_S7_EEEE (mutable iterator);
  state = dereferenceable;
  references sequence with type `NSt7__debug6vectorI11CMasternodeSaIS1_EEE' @ 0x0x117beb0
}
iterator "rhs" @ 0x0x7fd5faff6de0 {
type = N11__gnu_debug14_Safe_iteratorIN9__gnu_cxx17__normal_iteratorIP11CMasternodeNSt9__cxx19986vectorIS3_SaIS3_EEEEENSt7__debug6vectorIS3_S7_EEEE (mutable iterator);
  state = singular;
  references sequence with type `NSt7__debug6vectorI11CMasternodeSaIS1_EEE' @ 0x0x117beb0
}
```

and sometimes:

```
aegeusd: main.cpp:2031: bool ConnectBlock(const CBlock&, CValidationState&, CBlockIndex*, CCoinsViewCache&, bool): Assertion `hashPrevBlock == view.GetBestBlock()' failed.
```

Ubuntu Version:
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial

and pre-built release binary

**Comment by bkostjens** [comment]
I got the same problem with the pre-built binary. Currently running a self compiled instance in a screen session, to see if that fixes the problem.

**Comment by dehenne** [comment]
At the moment it runs, I made a reindex but it's not the best solution. *sigh*
I have a cron running which checks the status, now.

**Comment by bkostjens** [comment]
Maybe you can also try to build it yourself? So far it keeps running here, but yeah, it hasn't been long yet.

**Comment by bkostjens** [comment]
I uploaded my recompiled version to dropbox. It hasn't crash on me so far, but it's only running for a short time yet.

https://www.dropbox.com/s/rcgo3dyxva8ee84/Aegues-1.2-Ubuntu-16.04-X64-Recompiled.zip?dl=0

**Comment by dehenne** [comment]
my own self-compiled version looks a little better right now. my cpu load and server load was extremely high. with the compiled version its ok.

then we'll see how it goes on ^^

@AegeusCoin please look at the error. There some people who have the bug and where the nodes hardly run properly. Thank you.

**Comment by bkostjens** [comment]
Can you tell us a bit more about the issue? I have been compiling 1.2 from source, and so far (22h) is is running totally stable?

**Comment by AegeusCoin** [comment]
@bkostjens 

This line: https://github.com/AegeusCoin/aegeus/commit/c0463d240060b3c018f351421994a3518577ef4c#diff-031d4f9d201291e57fa6adbede2755a1R627

should have never been in there.  Since removed, there haven't been any issues running.  That was an error on our part, but during testing pre-release - this issue did not occur.

**Comment by AegeusCoin** [comment]
Please try this new build and let us know if issues still persist: https://github.com/AegeusCoin/aegeus/releases/download/1.2/Aegeus-1.2-Linux-64-bit.tar.gz

**Comment by dehenne** [comment]
interesting, as with @bkostjens, my self compiled node runs 2 days without errors and it's still running.
Are you sure this is the error? it makes no sense, our compiled version has this line, too ... :thinking:

**Comment by AegeusCoin** [comment]
@dehenne The compiled version is built and deployed from a private staging repo.  The current master public release is not the same.  We test code changes using that repo and once proven stable build the binaries from that source.  Have you tried the new build posted above?  We'll get to the root of the cause - whatever it may be.  You're welcome also, we're just doing our jobs.

**Comment by dehenne** [comment]
> The current master public release is not the same

well, how would you like your contribution guide to work, if your development version is not online?
and why is the dev version not available as a branch?

> Have you tried the new build posted above?

nope, because my node runs for three days.
